AWSTemplateFormatVersion: "2010-09-09"
Description: Creating Internet Gateway and attaching to an existing VPC

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID to attach the Internet Gateway

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${VpcId}-igw"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

Outputs:
  InternetGatewayId:
    Value: !Ref InternetGateway
    Description: ID of the created Internet Gateway
